variables:
  GIT_STRATEGY: clone

stages:
  - build

build-clang:
  stage: build
  tags:
    - clang
  script:
    - cd ..
    - mkdir build_clang
    - cd build_clang
    - source ../genten/scripts/sems_clang/setup_env.sh
    - ../genten/scripts/sems_clang/do_configure.sh
    - make -j8
    - ctest

build-gcc:
  stage: build
  tags:
    - gcc
  script:
    - cd ..
    - mkdir build_gcc
    - cd build_gcc
    - source ../genten/scripts/sems_gcc/setup_env.sh
    - ../genten/scripts/sems_gcc/do_configure.sh
    - make -j8
    - ctest

build-intel:
  stage: build
  tags:
    - intel
  script:
    - cd ..
    - mkdir build_intel
    - cd build_intel
    - source ../genten/scripts/sems_intel/setup_env.sh
    - ../genten/scripts/sems_intel/do_configure.sh
    - make -j8
    - ctest
