variables:
  GIT_STRATEGY: clone

stages:
  - build

build-clang:
  stage: build
  tags: 
    - clang
  script:
    - cd ..
    - mkdir build_clang
    - cd build_clang
    - source ../genten/scripts/sems_clang/setup_env.sh
    - /bin/bash ../genten/scripts/sems_clang/do_configure.sh
    - make -j8
    - ctest
